[mgr]
linemode       = "size"
[open]
rules = [
	# Folder
	{ name = "*/", use = [ "edit", "open", "reveal" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "open" ,"reveal" ] },
    { mime = "application/{*json*,*xml*,*yaml*,*script*,*text*,*plain*,*ini*,*csv*,*sql*,rtf,toml,javascript}" , use = [ "edit", "open" ,"reveal"]},
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	# Fallback
	{ name = "*", use = [ "open","edit","reveal" ] },
]
[opener]
edit= [
	{ run = '${EDITOR} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
	{ run = 'vim "$@"', desc = "vim", block = true, for = "unix" },
	{ run = 'vi "$@"', desc = "vi", block = true, for = "unix" },
	{ run = 'nvim %*',    block=true,    desc = "nvim",           for = "windows" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]
extract = [
  { run = '7z x "$@"', desc = "7z extract ", for = "unix" },
  { run = '7z x %*', desc = "7z extract", for = "windows" },
  { run = 'tar -xf "$@"', desc = "tar extract", for = "unix" },
  { run = 'tar -xf %*', desc = "tar extract", for = "windows" },
  { run = 'unzip "$@"', desc = "zip extract", for = "unix" },
  { run = 'unzip %*', desc = "zip extract", for = "windows" }
]
