#######################exec##########################
$ENV=/usr/bin/env LC_ALL=zh_CN
#$terminal= wezterm start --always-new-process
$terminal= env LANG=en_US.UTF-8 wezterm start --always-new-process
# $terminal= env LANG=en_US.UTF-8 kitty
exec-once = mkdir /tmp/$(whoami)/tmp
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user restart pipewire
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once=[workspace 1 silent ] $ENV $HOME/.local/opt/QQ/linuxqq.AppImage --force-device-scale-factor=1.5
exec-once=[workspace 2 silent ] $ENV /opt/YesPlayMusic/yesplaymusic --force-device-scale-factor=1.5 %U
exec-once=[workspace 3 silent ] $ENV env DESKTOPINTEGRATION=false /usr/bin/obsidian %u --no-sandbox  --force-device-scale-factor=1.5 %U
#exec-once=[workspace 3 silent] $ENV env DESKTOPINTEGRATION=false  $terminal  bash -c 'cd $OBSIDIAN ; ra ; zsh'
# exec-once=[workspace 4 silent ] $ENV google-chrome-stable --force-device-scale-factor=1.5
exec-once=[workspace 4 silent ] $ENV flatpak run --branch=stable --arch=x86_64 org.mozilla.firefox
exec-once=[workspace 5 silent ] $ENV telegram-desktop
exec-once=[workspace 6 silent ] $ENV $HOME/.local/opt/CFW/cfw 
exec-once=[workspace special silent] $terminal
exec-once=sleep 5 ; env QT_SCALE_FACTOR=1 flameshot
#务必置于最后
exec-once = ~/.autostart
