#######################exec##########################
$ENV=/usr/bin/env LC_ALL=zh_CN
# $terminal= env LANG=en_US.UTF-8 wezterm start --always-new-process
$terminal= $ENV wezterm start --always-new-process
# $terminal= env LANG=en_US.UTF-8 kitty
exec-once = mkdir /tmp/$(whoami)/tmp
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user restart pipewire
exec-once= systemctl --user start xsettingsd.service && echo "Xft.dpi: 144" | xrdb -merge

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once=[workspace 1 silent;float] $ENV env DESKTOPINTEGRATION=false /usr/bin/linuxqq --no-sandbox 
exec-once=[workspace 2 silent;tile] $ENV /opt/YesPlayMusic/yesplaymusic  --no-sandbox --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime 
exec-once=[workspace 3 silent;tile] $ENV env DESKTOPINTEGRATION=false /usr/bin/obsidian %u --no-sandbox --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime 
exec-once=[workspace 4 silent;tile] $ENV /usr/bin/google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --gtk-version=4 
exec-once=[workspace 5 silent;tile] $ENV telegram-desktop
exec-once=[workspace 6 silent;tile] $ENV $HOME/.local/opt/CFW/cfw 
exec-once=[workspace special  silent ; float ; size 83% 83%  ; center] $terminal
# bind = SUPER, E, exec, [workspace 2 silent;float;noanim] kitty

# exec-once=sleep 5 ; env QT_SCALE_FACTOR=1 flameshot
#务必置于最后
exec-once = ~/.autostart
