#######################rule##########################

windowrule = maximize ,^(logisim)$
windowrule = float,org.kde.polkit-kde-authentication-agent-1 
windowrule = float, file_progress
windowrule = float, confirm
windowrule = float, dialog
windowrule = float, download
windowrule = float, org.gnome.NautilusPreviewer
windowrule = float, notification
windowrule = float, error
windowrule = float, splash
windowrule = float, confirmreset
windowrule = float, title:Open File
windowrule = float, title:branchdialog
windowrule = float, Lxappearance
windowrule = float, Rofi
windowrule = animation none,Rofi
windowrule = float, viewnior
windowrule = float, Viewnior
windowrule = float, feh
windowrule = float, pavucontrol-qt
windowrule = float, pavucontrol
windowrule = float, file-roller
windowrule = float, title:DevTools
windowrule = fullscreen, wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrule = idleinhibit focus, mpv
windowrule = idleinhibit fullscreen, firefox
windowrule = float, title:^(Media viewer)$
windowrule = float, title:^(Volume Control)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = size 800 600, title:^(Volume Control)$
windowrule = move 75 44%, title:^(Volume Control)$
windowrule = opacity 0.92, Thunar

windowrule  = noborder, chromium
windowrule  = noborder, QQ
windowrule  = noborder, obsidian
windowrule  = noborder, ^(.*firefox.*)$
windowrule  = noborder, ^(.*yesplaymusic.*)$
windowrule  = opacity 1, ^(.*yesplaymusic.*)$
windowrule = noborder , xwayland = 1
windowrule = opacity 1 , ^(.*xournal.*)$
layerrule = blur , waybar
# windowrule = movetoworkspace special ,title:DrClientLinux
# windowrule = move 0 44%, ^(DrClientLinux)$
# windowrule = move 0 44%, title:^(.*DrClientLinux.*)$
windowrule = center , ^(pavucontrol)$
windowrule = float,title:画中画
windowrule = pin,title:画中画
# windowrule = pin,feh
windowrule = opacity 1 , firefox
windowrule = float, weixin
windowrule = float , xdg-desktop-portal-gtk
# windowrulev2 = opacity 1 override 0.85 override , xwayland:1
# windowrulev2 = opacity 1 override 0.85 override  , title:^(.*Chrome.*)$
# windowrulev2 = opacity 1 override  override  , title:^(.*chrome.*)$
windowrule = float , title:^(.*AriaNg.*)$

windowrulev2 =maximize, title:^(.*Chrome.*)$
windowrule = maximize , yesplaymusic
windowrule = maximize , Spotify
windowrule = nodim,windowdance,forceinput,MuseDash.exe
windowrule = nodim,windowdance,forceinput,musedash.exe
windowrule = nodim,windowdance,forceinput,Musedash.exe
windowrule = float , title:^(.*FPS.*)$

windowrule  = float,noanim ,^(.*flameshot.*)$
windowrule = float , maxsize  1920 1080 , ^(xdg-desktop-portal-gtk)$
windowrule = noanim , ^(.*Chrome.*)$
#windowrule = noanim , swaylock
# windowrule = noanim , jetbrains-studio
#windowrule = maxsize 2560 1390 , wp
#windowrule = move 0 50 , wps
windowrule = maximize , wps

windowrule = size , 1920 1440 , ^(.*game.exe.*)$
windowrule = maximize , ^(.*game.exe.*)$
windowrule = fullscreen , Waydroid 
#windowrule = float ,^(.*lutris.*)$
#windowrule = minsize  1920 1080 ,^(.*lutris.*)$
#windowrule = maxsize  1920 1080 ,^(.*lutris.*)$
#windowrule = size  1920 1080 ,^(.*lutris.*)$
#windowrulev2 = size  500 500,title:^(.*lutris.*)$
