#!/bin/sh
# The beginning of this script is both valid shell and valid python,
# such that the script starts with the shell and is reexecuted with
# the right python.
''':' && if [ ! -z "$MSYSTEM" ] ; then python "$0" "$@" ; else which python3 > /dev/null 2> /dev/null && python3 "$0" "$@" || python "$0" "$@" ; fi
'''
while True:
    print("Hello!")
